### ISSUE TITLE
Not sure why but it wouldn't work on windows 10 until I set mount_options

### ISSUE THREAD

**Issue by G4MR** [ncaroyannis/vagrant-php7#2]
I set this in the folder settings:

    :mount_options => ["dmode=777", "fmode=666"]

and didn't set a type and it worked fine on windows 10.  smb was causing issues and nfs never worked so I checked what scotchbox was doing and they never set a type, just the mount options and everything finally worked properly.

    config.vm.synced_folder folder["map"], folder["to"], :mount_options => ["dmode=777", "fmode=666"], type: folder["type"] ||= nil

**Comment by ncaroyannis** [comment]
Might be worth adding this plugin for NFS Windows support: https://github.com/winnfsd/vagrant-winnfsd

I'll take a look about SMB support in the future, haven't tested it yet.

Thanks for the information, though, I may include that in future versions as a fallback.

**Comment by G4MR** [comment]
Alright that seems to work, not sure why this is appearing though even though everything seems to be working, no php7 errors.  Seems odd.

    ==> default: Module php7 already enabled
    ==> default: Running provisioner: shell...
        default: Running: inline script
    ==> default: stdin: is not a tty
    ==> default: httpd not running, trying to start
    ==> default: httpd not running, trying to start

**Comment by ncaroyannis** [comment]
Don't worry about that - they're just notices you can safely ignore.
