### ISSUE TITLE
NFS problem

### ISSUE THREAD

**Issue by matiux** [ncaroyannis/vagrant-php7#3]
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.7.1:'/var/www/Php7/Others' /var/www/html

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: requested NFS version or transport protocol is not supported
```

How can I solve?

**Comment by ncaroyannis** [comment]
Could you provide me with some more information? What is your operating system, and can you provide a full log of the output from 'vagrant up'?

See: https://docs.vagrantup.com/v2/other/debugging.html

**Comment by G4MR** [comment]
I get this error sometimes, make sure your anti-virus is in low priority or off and just provision a few times and it should work.  It does happen more often than not though.  Also changing the ports/ip also helps sometimes
