### ISSUE TITLE
Can you add a script for upgrading PHP 7

### ISSUE THREAD

**Issue by G4MR** [ncaroyannis/vagrant-php7#5]
I'm still fairly new to the linux side of things so my abilities with linux is limited (I wouldn't come to me if someone needed a linux system admin lol) so I'm wondering if it would be easy to make a script for rebuilding PHP 7 from the source using a command with 7.0.1 being released I doubt you'd have time to push every new PHP 7 release.

**Comment by ncaroyannis** [comment]
Feel free to submit a pull request with a script to do so and I'll include it. Thanks!
